# Form implementation generated from reading ui file 'settings.ui'
#
# Created by: PyQt6 UI code generator 6.6.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Settings(object):
    """Class represents Dialog window for setting parameters for creating Contour Lines"""

    def setupUi(self, Settings):
        Settings.setObjectName("Settings")
        Settings.resize(296, 214)
        self.buttonBox = QtWidgets.QDialogButtonBox(parent=Settings)
        self.buttonBox.setGeometry(QtCore.QRect(10, 170, 271, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.StandardButton.Cancel|QtWidgets.QDialogButtonBox.StandardButton.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.groupBox = QtWidgets.QGroupBox(parent=Settings)
        self.groupBox.setGeometry(QtCore.QRect(10, 10, 271, 151))
        self.groupBox.setObjectName("groupBox")
        self.splitter = QtWidgets.QSplitter(parent=self.groupBox)
        self.splitter.setGeometry(QtCore.QRect(10, 40, 176, 101))
        self.splitter.setOrientation(QtCore.Qt.Orientation.Vertical)
        self.splitter.setObjectName("splitter")
        self.label = QtWidgets.QLabel(parent=self.splitter)
        self.label.setObjectName("label")
        self.label_3 = QtWidgets.QLabel(parent=self.splitter)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(parent=self.splitter)
        self.label_4.setObjectName("label_4")
        self.splitter_2 = QtWidgets.QSplitter(parent=self.groupBox)
        self.splitter_2.setGeometry(QtCore.QRect(200, 40, 41, 101))
        self.splitter_2.setOrientation(QtCore.Qt.Orientation.Vertical)
        self.splitter_2.setObjectName("splitter_2")
        self.minVal = QtWidgets.QLineEdit(parent=self.splitter_2)
        self.minVal.setObjectName("minVal")
        self.maxVal = QtWidgets.QLineEdit(parent=self.splitter_2)
        self.maxVal.setObjectName("maxVal")
        self.intVal = QtWidgets.QLineEdit(parent=self.splitter_2)
        self.intVal.setObjectName("intVal")
        self.splitter_3 = QtWidgets.QSplitter(parent=self.groupBox)
        self.splitter_3.setGeometry(QtCore.QRect(250, 40, 20, 101))
        self.splitter_3.setOrientation(QtCore.Qt.Orientation.Vertical)
        self.splitter_3.setObjectName("splitter_3")
        self.label_2 = QtWidgets.QLabel(parent=self.splitter_3)
        self.label_2.setObjectName("label_2")
        self.label_5 = QtWidgets.QLabel(parent=self.splitter_3)
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(parent=self.splitter_3)
        self.label_6.setObjectName("label_6")

        self.retranslateUi(Settings)
        self.buttonBox.accepted.connect(Settings.accept) # type: ignore
        self.buttonBox.rejected.connect(Settings.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Settings)

    def retranslateUi(self, Settings):
        _translate = QtCore.QCoreApplication.translate
        Settings.setWindowTitle(_translate("Settings", "Dialog"))
        self.groupBox.setTitle(_translate("Settings", "Contour line parameters"))
        self.label.setText(_translate("Settings", "Minimum Contour line height: "))
        self.label_3.setText(_translate("Settings", "Maximum Contour line height: "))
        self.label_4.setText(_translate("Settings", "Contour line interval: "))
        self.minVal.setText(_translate("Settings", "0"))
        self.maxVal.setText(_translate("Settings", "1610"))
        self.intVal.setText(_translate("Settings", "100"))
        self.label_2.setText(_translate("Settings", "m"))
        self.label_5.setText(_translate("Settings", "m"))
        self.label_6.setText(_translate("Settings", "m"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Settings = QtWidgets.QDialog()
    ui = Ui_Settings()
    ui.setupUi(Settings)
    Settings.show()
    sys.exit(app.exec())